// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB5ZjJX5STGcFEkf-4clZucceY07hWbTA',
    appId: '1:738599167122:web:0bff87ad58b55ba01eb24b',
    messagingSenderId: '738599167122',
    projectId: 'flutter-the-wall',
    authDomain: 'flutter-the-wall.firebaseapp.com',
    storageBucket: 'flutter-the-wall.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5XyPeptdtdQn-heWFWtptHqrliARwp8',
    appId: '1:738599167122:android:945f3e523cc997431eb24b',
    messagingSenderId: '738599167122',
    projectId: 'flutter-the-wall',
    storageBucket: 'flutter-the-wall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6rurqbtj8Wzn3y0-w9xg-ujUHnXoTKWI',
    appId: '1:738599167122:ios:829e5b77dc33b8a01eb24b',
    messagingSenderId: '738599167122',
    projectId: 'flutter-the-wall',
    storageBucket: 'flutter-the-wall.appspot.com',
    iosClientId: '738599167122-p4ufnlqdg74dagk1guv02005addfme87.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6rurqbtj8Wzn3y0-w9xg-ujUHnXoTKWI',
    appId: '1:738599167122:ios:96a150f5a5591be31eb24b',
    messagingSenderId: '738599167122',
    projectId: 'flutter-the-wall',
    storageBucket: 'flutter-the-wall.appspot.com',
    iosClientId: '738599167122-59o8d4uc7mq3fledo8qn0ft1ec5q412p.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWall.RunnerTests',
  );
}
